apiVersion: unagex.com/v1
kind: Metabase
metadata:
  labels:
    app.kubernetes.io/name: metabase
    app.kubernetes.io/instance: metabase-sample
    app.kubernetes.io/part-of: metabase-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metabase-operator
  name: metabase-sample
spec:
  # TODO(user): Add fields here
