name: Build and push docker image to github

on:
  push:
    paths:
      - charts/**

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          # read the helm chart version
          export VERSION=$(grep version charts/operator/Chart.yaml | awk '{print $2}')
          make docker-build
          make docker-push